import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const appSource = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')

describe('MVP editor wiring', () => {
  it('keeps the standalone injector and adds the Studio GLB SPACE workspace', () => {
    expect(appSource).toContain('GLB模型数据注入')
    expect(appSource).toContain('navigateToGlbInjection')
    expect(appSource).toContain('resolveGlbInjectionUrl')
    expect(appSource).toContain('GLB 模型数据注入服务未启动，请在项目目录运行 npm run injector')
    expect(appSource).toContain('ref="glbInput"')
    expect(appSource).toContain('function importGlb')
    expect(appSource).toContain('原 GLB 节点（只读）')
    expect(appSource).toContain('selectedExternalNode')
    expect(appSource).toContain('@external-load-error')
    expect(appSource).toContain('externalWorkspace')
    expect(appSource).toContain('导入 GLB 补空间')
  })

  it('keeps automatic SPACE inference transient until explicit human confirmation', () => {
    expect(appSource).toContain('detectExternalSpaceCandidates')
    expect(appSource).toContain('externalGeometryCache')
    expect(appSource).toContain('spaceDetectionRequest')
    expect(appSource).toContain('externalWorkspace.value!==workspace')
    expect(appSource).toContain('sourceFloorId')
    expect(appSource).toContain('TransientCandidateHistory')
    expect(appSource).toContain('selectedEntityIds:selectedIds.value')
    expect(appSource).toContain('restoreHistorySelection(candidateValue)')
    expect(appSource).toContain('spaceCandidates=ref<ExternalSpaceCandidateDraft[]>([]),selectedCandidateIds=ref<string[]>([])')
    expect(appSource).toContain('activeSpaceCandidates=computed')
    expect(appSource).toContain('candidate.floorId===floor.value.id')
    expect(appSource).toContain(':space-candidates="spaceCandidatePreviews"')
    expect(appSource).toContain('@candidate-select="selectSpaceCandidate"')
    expect(appSource).toContain('@candidate-selection="applyCandidateViewportSelection"')
    expect(appSource).toContain(':selected-candidate-ids="selectedCandidateIds"')
    expect(appSource).toContain('自动候选 SPACE')
    expect(appSource).toContain('确认写入 SPACE')
    expect(appSource).toContain('confirmExternalSpaceCandidates')
    expect(appSource).toContain('手绘修正边界')
    expect(appSource).toContain('existingSpaces')
    expect(appSource).toContain('window-boundary-closed')
    expect(appSource).toContain('skippedMultiContourRegionCount')
    expect(appSource).toContain('source-space-boundary-unavailable')
    expect(appSource).toContain('matchingStats.maxOperationsExceeded')
    expect(appSource).toContain('sourceSpaceStats.maxOperationsExceeded')
    expect(appSource).toContain('自动候选已停止，请使用手绘修正')
    expect(appSource).toContain("drafts.find(candidate=>candidate.confidence==='inferred-high')")
    expect(appSource).toContain('已保护源 GLB 的')
    expect(appSource).toContain('function confirmSelectedSpaceCandidates')
    expect(appSource).toContain('统一确认 {{selectedCandidates.length}} 个 SPACE')
  })

  it('routes single and batch Space Type edits through atomic Domain commands', () => {
    expect(appSource).toContain('updateSpaceTypeForEntity')
    expect(appSource).toContain('updateSpaceTypeForEntities')
    expect(appSource).toContain('canBatchEditSpaceType')
    expect(appSource).toContain('function applySpaceTypeUpdate')
    expect(appSource).toContain('function updateSelectedSpaceTypes')
    expect(appSource).toContain('function updateSingleSpaceType')
    expect(appSource).toContain('const source=JSON.parse(JSON.stringify(project.value)) as Project,next=update(source)')
    expect(appSource).toContain('source=>updateSpaceTypeForEntities(source,entityIds,spaceType)')
    expect(appSource).toContain('source=>updateSpaceTypeForEntity(source,entity.id,spaceType)')
    expect(appSource).toContain('已修改并人工确认 SPACE 类型，可撤销')
    expect(appSource).toContain('批量空间属性')
    expect(appSource).toContain('@change="updateSelectedSpaceTypes"')
    expect(appSource).toContain('@change="updateSingleSpaceType"')
    expect(appSource).not.toContain('e.spaceType=')
  })

  it('exposes useful hierarchy context actions and confirms destructive cascades', () => {
    expect(appSource).toContain('getTreeContextActions')
    expect(appSource).toContain('runContextAction(action.id)')
    expect(appSource).toContain('buildHierarchyDeletionImpact')
    expect(appSource).toContain("title:'删除墙体及宿主门窗？'")
    expect(appSource).toContain('class="confirmation-backdrop"')
  })

  it('connects viewport safety, continuous wall drawing and real snap state', () => {
    const onCreateSource = appSource.slice(appSource.indexOf('function onCreate'), appSource.indexOf('function deleteEntities'))
    expect(appSource).toContain(':snap-enabled="project.settings.snapEnabled"')
    expect(appSource).toContain(':wall-height="floor.clearHeight"')
    expect(appSource).toContain(':wall-thickness="0.2"')
    expect(onCreateSource).not.toContain("tool.value='选择'")
    expect(appSource).not.toContain('@exit-tool=')
    expect(appSource).toContain('polygon:payload.polygon')
    expect(appSource).toContain('@wall-rejected=')
    expect(appSource).toContain('cancelViewportInteraction()')
  })

  it('guards locked edits, repairs stale editor ids, and protects dirty replacement flows', () => {
    expect(appSource).toContain(':disabled="selected.locked"')
    expect(appSource).toContain('normalizeEditorState')
    expect(appSource).toContain('guardUnsaved')
    expect(appSource).toContain("secondaryLabel:'放弃修改'")
  })
})
